### ISSUE TITLE
Styling Issues specifity

### ISSUE THREAD

**Issue by Vespilo** [MrPrimate/tokenizer#144] opened 2023-11-21 09:43 UTC
The colours for optgroups are specified via "#tokenizer option, optgroup" which can lead to unwanted style issues with unrelated modules or systems. For consistency it should probably be "#tokenizer option, #tokenizer optgroup"

**Comment by MrPrimate** [comment] 2023-11-22 09:29
I'm not sure I fully follow the issue here, can you look at the CSS https://github.com/MrPrimate/tokenizer/blob/e72f85038db16735083c5461793a85e1851041e1/css and pull out an example for me? Happy to correct, just not sure where the problem is.

**Comment by MrPrimate** [comment] 2023-11-22 09:31
Thanks, fixed in next release

**Closed by MrPrimate** 2023-11-22 09:31 UTC
