### ISSUE TITLE
Bug : Token image resize down

### ISSUE THREAD

**Issue by JordanRR** [MrPrimate/tokenizer#110] opened 2022-12-19 11:08 UTC
Not a big bug (mayube not even a bug?), but annoying : the token image resizes down when I open the Tokenizer menu. When I use the avatar image, the size is fine, so I save it (and the actual token is fine). But then, if I open the menu again, the token image is downsized, and if I save it, the actual token image is smaller.

Here is a screenshot : 
![image](https://user-images.githubusercontent.com/18445516/208412117-79510733-773e-4e6b-9e13-9f18926f57ee.png)

The size appears to be just small enough to let a frame circle the image. Here is a screenshot with the automatically added frame :
![image](https://user-images.githubusercontent.com/18445516/208412486-0219facc-aa40-4244-b033-6f0334aa2090.png)

Thanks!

**Comment by MrPrimate** [comment] 2022-12-19 13:42
Tokenizer offsets images it finds a little and shrinks them to fit in the token ring so you can see more of the image. If this is not your desired behaviour, change the "Default Token Offset" value from -35 to 0 in the module settings.

Possible duplicate of #83

**Closed** 2022-12-19 13:42 UTC

**Comment by JordanRR** [comment] 2022-12-19 14:13
Thank you very much for the quick reply! Happy holidaysto you and yours 😄
